[2024-10-11T21:50:00.874+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: nba_data_pipeline.create_tables scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-10-11T21:50:00.890+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: nba_data_pipeline.create_tables scheduled__2023-10-02T00:00:00+00:00 [queued]>
[2024-10-11T21:50:00.891+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T21:50:00.892+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-10-11T21:50:00.893+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-10-11T21:50:00.953+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): create_tables> on 2023-10-02 00:00:00+00:00
[2024-10-11T21:50:00.972+0000] {standard_task_runner.py:55} INFO - Started process 118 to run task
[2024-10-11T21:50:01.004+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nba_data_pipeline', 'create_tables', 'scheduled__2023-10-02T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/nba_data_pipeline.py', '--cfg-path', '/tmp/tmpil1bkch5']
[2024-10-11T21:50:01.021+0000] {standard_task_runner.py:83} INFO - Job 44: Subtask create_tables
[2024-10-11T21:50:01.245+0000] {task_command.py:388} INFO - Running <TaskInstance: nba_data_pipeline.create_tables scheduled__2023-10-02T00:00:00+00:00 [running]> on host eccc01d8c48f
[2024-10-11T21:50:01.456+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nba_data_pipeline
AIRFLOW_CTX_TASK_ID=create_tables
AIRFLOW_CTX_EXECUTION_DATE=2023-10-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-10-02T00:00:00+00:00
[2024-10-11T21:50:01.460+0000] {logging_mixin.py:137} INFO - Error: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
[2024-10-11T21:50:01.466+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/scripts/create_tables.py", line 75, in create_tables
    if conn is not None:
UnboundLocalError: local variable 'conn' referenced before assignment
[2024-10-11T21:50:01.498+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=nba_data_pipeline, task_id=create_tables, execution_date=20231002T000000, start_date=20241011T215000, end_date=20241011T215001
[2024-10-11T21:50:01.518+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 44 for task create_tables (local variable 'conn' referenced before assignment; 118)
[2024-10-11T21:50:01.566+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-10-11T21:50:01.614+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
